export default function Head() {
  return (
    <>
      <title>todoList</title>
      <link rel="stylesheet" precedence="default" href="/fonts/dana.min.css" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
